### PR TITLE
Added context to the issue reporting link

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Fixes https://github.com/UAVCAN/uavcan.github.io/issues/9

### CODE REVIEW

**Comment by hamishwillee** [comment]
It looks good (though I haven't built this to test). 

Any reason why you decided not to have the page title in the issue title as well? It isn't a big deal, but it makes things a little easier to scan sets of bug reports if they don't all have the same title.

**Comment by pavel-kirienko** [comment]
No reason at all. Moved the page URL into the title section, should be good enough now.

**Comment by hamishwillee** [comment]
Works for me. Is certainly better than before/good enough for now.

Just because I am pedantic:
* Having the title rather than URL in issue subject is usually better, because sometimes titles and URLs are out of sync, or URLS are too long.
* It is still useful to have the actual URL pre-seeded in the body because then you can make this a "full link" to the problem page - either in rendered form or the page that the checker will need to edit. Just makes it a tiny bit easier to find the page.
* Depending on your user base it can also be useful to seed the body with instructional text - e.g. "ENTER description of problem here, don't forget to include versions tested etc etc"

**Comment by pavel-kirienko** [comment]
Your propositions make sense. However, we have received exactly zero bug reports via this link so far, so we shouldn't waste too much time on it. Frustrated users tend to turn up on the mailing list or in the chat room instead.

> sometimes titles and URLs are out of sync

Not possible, because in this application, titles and URLs are tightly bound. Titles are, in fact, generated automatically from URLs.

**Comment by hamishwillee** [comment]
Good point!

**Pull request merged**
