### PR TITLE
Editorial updates to spec6_ app level functions

### PR DESCRIPTION
**Pull request by hamishwillee**
General review and tidy up. Additional comments to follow.

### CODE REVIEW

**Comment by hamishwillee** [comment]
The following included messages had errors or questions (but are not part of this doc)

----

uavcan.protocol.NodeStatus

Any UAVCAN node is required to publish this message periodically.
=>
All UAVCAN nodes are required to publish this message periodically.

--- 

uavcan.protocol.GlobalTimeSync

> Synchronization slaves may switch to a new source if the current master was silent for this amount of time.

May or must?

-----

> ## Node configuration

The list generated by the include in this sectionis bigger than the list that describes it. Order is wrong too. 

> {% include dsdl.md prefix='uavcan.protocol.param.' %}

---

uavcan.protocol.param.GetSet

> # Note that access by index should only be used to retreive the list of parameters; it is higly
=>
Typo: retreive => retreive
Typo: higly => highly

----

uavcan.protocol.file.BeginFirmwareUpdate

uint8 ERROR_IN_PROGRESS      = 2    # Firmware update is already in progess, and the slave doesn't want to restart.
Typo: progess => progress

---

uavcan.protocol.AccessCommandShell
> # handler itself, which interpretes it. 
Typo: interpretes => interprets


----

uavcan.protocol.dynamic_node_id.Allocation

> # - Followup delay - Tfollowup.
Maybe:  Follow up delay

> Recommended randomization ranges for these intervals are documented in the costants
Typo: costants => constants

> # prefferred node ID upward, untill a free node ID is found. If a free node ID could not be found, the
Typo: prefferred
Typo: untill


----
uavcan.protocol.param.Empty

#
# Ex nihilo nihil fit.

> Pleasing to see you know your latin, but should this be in English?


---

uavcan.protocol.file.GetDirectoryEntryInfo

> This service can be used to retrieve remote directory listing, one entry per request.
=> retrieve a remote ....

-----

uavcan.protocol.debug.KeyValue

>  Integers are exactly representable in the range (-2^24, 2^24) which is (-16'777'216, 16'777'216).

"(-16'777'216, 16'777'216)." - this looks odd in English.

**Comment by hamishwillee** [comment]
There is a line 

> Panic message allows to quickly shut down the system in an event of emergency.

"allows to" makes no sense. Allows what?

**Comment by pavel-kirienko** [comment]
@hamishwillee would it be possible to extend our current arrangement to also include fixing the comments in the standard DSDL definitions? The DSDL repository can be found here https://github.com/UAVCAN/dsdl

I am going to respond to your questions later.

**Comment by hamishwillee** [comment]
The naming is updatee and allocatee are not "real English" AFAIK, but I don't know of any other more accurate terms. 

- uavcan.protocol.file.BeginFirmwareUpdate uses slave and initiator
- Options update-target, update-recipient, update-requestor,

**Comment by hamishwillee** [comment]
We refer to applications at the top, but nodes everywhere else - could these terms be considered interchangable?

**Comment by hamishwillee** [comment]
A lot of the explanation explaining how static nodes can work with dynamic allocation didn't make sense to me, but may well to others. 

E.g. 
"If the node failed to respond to uavcan.protocol.GetNodeInfo after at least 3 attempts, the allocator will extend the allocation table with a mock entry, where the node ID is matching the real node ID of the non-responding node, and unique ID is set to zero. This ensures that dynamic nodes will not be granted a node ID value that is already taken by a static node." 

So you actually have the real node ID from the new node even if it doesn't respond to  uavcan.protocol.GetNodeInfo? YOu add this to the allocation table, so that no other node can be allocated it. Why do we set the unique ID to zero? - because we don't know it?

Anyway, I think/guess the way it works is that something that is dynamically allocated requests a id, while a static node doesn't, but gets detected, and the allocator saves its spot based on node information it gets when it detects the node. 

----

This didn't mean anything to me.

> Note that this restriction does not apply to allocation requests sent via CAN FD frames, as in this case no follow-up responses are necessary. So only CAN FD can offer perfectly reliable allocation exchanges.

----
I also found the whole following discussion/example confusing. I think the problem is I really don't understand the domain - so it isn't clear why B being in a minor partition means that it can't commit to the raft log. Might be good for you to read and see if it makes sense to you assuming a less than expert reader ...

> Consider a case with two Raft nodes that are residing in different network partitions, unable to communicate with each other - A and B, both of them are leaders; A can commit to the log, and B is in a minor partition. ....

**Comment by hamishwillee** [comment]
> @hamishwillee would it be possible to extend our current arrangement to also include fixing the comments in the standard DSDL definitions? The DSDL repository can be found here https://github.com/UAVCAN/dsdl

Possibly. I'm loath to commit too far in the future.  

We can certainly put the comments I made about these in a separate issue, assign to me, and if we have time after I've finished the main specs we can get to them?

> I am going to respond to your questions later.

No urgency :-) Lots to do!

**Comment by pavel-kirienko** [comment]
> All UAVCAN nodes are required to publish this message periodically.

Fixed.

> May or must?

"May", left unchanged.

> The list generated by the include in this sectionis bigger than the list that describes it. Order is wrong too.

The objective of the list is to highlight the most important entries. It is not the intention to list every single of the following items there - why would we need that, they are listed right there anyway.

> Typo: retreive => retreive
> Typo: higly => highly

Fixed.

> Typo: progess => progress

Fixed.

> Typo: interpretes => interprets

Fixed.

> Maybe: Follow up delay

Changed.

> Typo: prefferred
> Typo: untill

Fixed.

> Pleasing to see you know your latin, but should this be in English?

No.

> => retrieve a remote ....

Fixed.

> "(-16'777'216, 16'777'216)." - this looks odd in English.

I wanted to keep the description close to the syntax conventions used in programming languages. I know that in English you may want to use commas here, but programming languages are reluctant to adopt commas as thousands separators because that may lead to dangerously confusing literals. C++ uses the quotation mark for this purpose, so I decided to use it here, too. It's more readable than Ada's and Python's underscores, I think.

-----

> > Panic message allows to quickly shut down the system in an event of emergency.

> "allows to" makes no sense. Allows what?

Allows the broadcaster to shut down the system... Does it read better?

-----

> The naming is updatee and allocatee are not "real English" AFAIK, but I don't know of any other more accurate terms.

Oh yes. They were proposed by an Australian and Amerian guys, I figured that if they found it acceptable, I shouldn't worry about that. Let us suppose that bending English like that here is acceptable.

> uavcan.protocol.file.BeginFirmwareUpdate uses slave and initiator
> Options update-target, update-recipient, update-requestor,

Are you proposing to rename "slave" into "update-target" and "initiator" into "update-requestor"? I'm not against that, but frankly both seem rather equivalent to me. I don't have much room to speak here though, my English is imperfect at its best.

-----

> We refer to applications at the top, but nodes everywhere else - could these terms be considered interchangable?

Generally yes, but there is a subtle difference: "node" is typically a hardware thing; "application" is something that is being executed on the node.

-----

> So you actually have the real node ID from the new node even if it doesn't respond to uavcan.protocol.GetNodeInfo?

Yes, node ID is always known.

> YOu add this to the allocation table, so that no other node can be allocated it. Why do we set the unique ID to zero? - because we don't know it?

Yes.

> Anyway, I think/guess the way it works is that something that is dynamically allocated requests a id, while a static node doesn't, but gets detected, and the allocator saves its spot based on node information it gets when it detects the node.

Correct.

> Note that this restriction does not apply to allocation requests sent via CAN FD frames, as in this case no follow-up responses are necessary. So only CAN FD can offer perfectly reliable allocation exchanges.

CAN FD allows CAN frames to be larger, so that the allocatee and the allocator can exchange the necessary information in just one request and one response. They don't have to split their comms over multiple messages. Should we explicitly describe what is CAN FD?

> I also found the whole following discussion/example confusing. I think the problem is I really don't understand the domain - so it isn't clear why B being in a minor partition means that it can't commit to the raft log.

It is explained in the Raft paper linked from the beginning, so I think it should be OK to leave it as is.

**Comment by hamishwillee** [comment]
>> "(-16'777'216, 16'777'216)." - this looks odd in English.

> I wanted to keep the description close to the syntax conventions used in programming languages. I know that in English you may want to use commas here, but programming languages are reluctant to adopt commas as thousands separators because that may lead to dangerously confusing literals. C++ uses the quotation mark for this purpose, so I decided to use it here, too. It's more readable than Ada's and Python's underscores, I think.

Sounds reasonable.

**Comment by hamishwillee** [comment]
>>> Panic message allows to quickly shut down the system in an event of emergency.

>> "allows to" makes no sense. Allows what?

> Allows the broadcaster to shut down the system... Does it read better?

"Allows to" is never correct.  Has be "allows *something* to". 

Your suggestion is fine, but to just tidy up the  original sentence you could do:

The panic message allows the broadcaster to quickly shut down the system in the event of an emergency.

**Comment by hamishwillee** [comment]
>> The naming is updatee and allocatee are not "real English" AFAIK, but I don't know of any other more accurate terms.

> Oh yes. They were proposed by an Australian and Amerian guys, I figured that if they found it acceptable, I shouldn't worry about that. Let us suppose that bending English like that here is acceptable.

I agree. There are some Microsoft docs that use the same convention, so it isn't a completely new construct.

>> uavcan.protocol.file.BeginFirmwareUpdate uses slave and initiator

>Options update-target, update-recipient, update-requestor,

> Are you proposing to rename "slave" into "update-target" and "initiator" into "update-requestor"? I'm not against that, but frankly both seem rather equivalent to me. I don't have much room to speak here though, my English is imperfect at its best.

Actually I was only showing "slave" to show one alternative doc for updatee that we use in our docs - but I omitted the explanation for that sorry. 

I was proposing we consider update-target, update-recipient, update-requestor, as possible alternatives to updatee.

But that was just a proposal. None of them are actually better.

**Comment by hamishwillee** [comment]
>> We refer to applications at the top, but nodes everywhere else - could these terms be considered interchangable?

> Generally yes, but there is a subtle difference: "node" is typically a hardware thing; "application" is something that is being executed on the node.

OK, that is helpful (for me). Thanks. No docs change needed.

**Comment by hamishwillee** [comment]
>> Note that this restriction does not apply to allocation requests sent via CAN FD frames, as in this case no follow-up responses are necessary. So only CAN FD can offer perfectly reliable allocation exchanges.

> CAN FD allows CAN frames to be larger, so that the allocatee and the allocator can exchange the necessary information in just one request and one response. They don't have to split their comms over multiple messages. 

> Should we explicitly describe what is CAN FD?

Possibly, or you could just spell it out here ...

Note that this restriction does not apply to allocation requests sent via CAN FD frames as these allow larger frames such that all necessary information to be exchanged in a single request and response. Only CAN FD can offer perfectly reliable allocation exchanges!

**Comment by hamishwillee** [comment]
Re your comments about ...

> "If the node failed to respond to uavcan.protocol.GetNodeInfo after at least 3 attempts, the allocator will extend the allocation table with a mock entry, ...

Thanks for confirmation. I'm OK with the current text.

**Comment by hamishwillee** [comment]
@pavel-kirienko OK, so comments above that have actions are:
-  https://github.com/UAVCAN/uavcan.github.io/pull/28#issuecomment-342036492
- https://github.com/UAVCAN/uavcan.github.io/pull/28#issuecomment-342034802

Otherwise good to merge IMO.

**Comment by pavel-kirienko** [comment]
Thanks @hamishwillee !

**Comment by hamishwillee** [comment]
YOu are very welcome! I'll try move onto the next spec this week

**Pull request merged**
